version: "3.8"

services:
  # api:
  #   image: "crawler:latest"
  #   env_file: .env
  #   ports:
  #     - 3003:3000
  # worker:
  #   image: "crawler:latest"
  #   env_file: .env
  #   command: ["worker", "--worker_function","get_html_worker"]

  # faktory:
  #   image: contribsys/faktory
  #   volumes:
  #     - faktory-data:/var/lib/faktory
  #   depends_on:
  #     - db
  #   ports:
  #     - 7419:7419
  #     - 7420:7420

  db:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./.docker-compose/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  # localstack:
  #   image: localstack/localstack:0.12.15
  #   environment:
  #     SERVICES: s3,sns,sqs
  #     DEBUG: 1
  #     DEFAULT_REGION: eu-central-1
  #     DATA_DIR: /tmp/localstack/data
  #   volumes:
  #     - ./.docker-compose/localstack/initaws.d:/docker-entrypoint-initaws.d

volumes:
  db-data:
    driver: local
  go-modules:
    driver: local
  faktory-data:
    driver: local
