apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server-deployment
  labels:
    app: api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
        -
          name: crawler-api
          image: crawler:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            -
              name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: api-server-secrets
                  key: database_host
            -
              name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: api-server-secrets
                  key: database_port
            -
              name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: api-server-secrets
                  key: database_user
            -
              name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-server-secrets
                  key: database_password
            -
              name: DATABASE_DB
              valueFrom:
                secretKeyRef:
                  name: api-server-secrets
                  key: database_name
            -
              name: APP_ENV
              valueFrom:
                secretKeyRef:
                  name: api-server-secrets
                  key: app_env
            -
              name: FAKTORY_URL
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: faktory_url

