apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: crawler
spec:
  selector:
    app: api
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      #nodePort: 30000 #30000 - 32767
