apiVersion: v1
kind: Service
metadata:
  name: faktory
spec:
  selector:
    app: faktory
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 7420
      targetPort: 7420
      nodePort: 30001 #30000 - 32767
