apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  namespace: crawler
  labels:
    app: worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      imagePullSecrets:
        - name: mydockerreg
      containers:
        -
          name: worker
          image: hub.normans.co.za/crawler:0.0.3
          command:
            - "worker"
            - "--worker_function"
            - "get_html_worker"
          env:
            -
              name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: database_host
            -
              name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: database_port
            -
              name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: database_user
            -
              name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: database_password
            -
              name: DATABASE_DB
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: database_name
            -
              name: APP_ENV
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: app_env
            -
              name: FAKTORY_URL
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: faktory_url

